# Generated by Django 3.2.25 on 2024-04-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0002_fin_creditnote1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fin_CreditNote1',
        ),
    ]
